name: Initialization
description: This action initializes COSMO Alpaca
author: COSMO CONSULT
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
outputs:
  backendUrl:
    description: COSMO Alpaca Backend URL
    value: ${{ steps.Initialization.outputs.backendUrl }}
  scriptsArchiveUrl:
    description: COSMO Alpaca Scripts Archive URL
    value: ${{ steps.Initialization.outputs.scriptsArchiveUrl }}
  scriptsArchiveDirectory:
    description: COSMO Alpaca Scripts Archive Directory
    value: ${{ steps.Initialization.outputs.scriptsArchiveDirectory }}
runs:
  using: composite
  steps:
    - id: CheckDeprecatedConfig
      name: COSMO Alpaca Check for Deprecated Config
      shell: ${{ inputs.shell }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api repos/${{ github.repository }}/contents/.alpaca/alpaca.json?ref=${{ github.sha }} --silent 2>$null
        if ($LASTEXITCODE -eq 0) {
          Write-Host "::warning::The configuration file '.alpaca/alpaca.json' is deprecated.%0AThis will become an error in the future.%0A%0APlease migrate to AL-Go settings.%0ASee: https://docs.cosmoconsult.com/en-us/cloud-service/devops-docker-selfservice/containers/setup-cosmo-json.html"
        }
        exit 0

    - id: Initialization
      name: COSMO Alpaca Initialization
      shell: ${{ inputs.shell }}
      env:
        _actionRepo: ${{ github.action_repository }}
        _actionRef: ${{ github.action_ref }}
      run: |
        ${{ github.action_path }}/Initialization.ps1 -ActionRepo $env:_actionRepo -ActionRef $env:_actionRef
branding:
  icon: terminal
  color: blue
