name: Get Configs For Sync
description: This action finds all secret names from AL-Go settings and Alpaca backend, and encodes specified variables to prepare for synchronization
author: COSMO CONSULT
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  mode:
    description: Mode for the action - 'GetAndUpdate' searches AL-Go settings files and backend, 'Update' only queries backend
    required: false
    default: GetAndUpdate
  additionalSecrets:
    description: Comma-separated list of additional secret names to always include
    required: false
    default: ''
  allVariables:
    description: All GitHub variables as JSON string (from toJson(vars))
    required: false
    default: '{}'
  additionalVariables:
    description: Comma-separated list of variable names to include and base64-encode
    required: false
    default: ''
outputs:
  secretsForSync:
    description: Comma-separated list of distinct secret names found in AL-Go settings and Alpaca backend
    value: ${{ steps.GetConfigsForSync.outputs.secretsForSync }}
  Variables:
    description: JSON object with unencoded variable values
    value: ${{ steps.GetConfigsForSync.outputs.Variables }}
runs:
  using: composite
  steps:
    - id: GetConfigsForSync
      name: Get COSMO Alpaca Configs For Sync
      shell: ${{ inputs.shell }}
      env:
        _token: ${{ inputs.token }}
        _mode: ${{ inputs.mode }}
        _additionalSecrets: ${{ inputs.additionalSecrets }}
        _allVariables: ${{ inputs.allVariables }}
        _additionalVariables: ${{ inputs.additionalVariables }}
      run: |
        ${{ github.action_path }}/GetConfigsForSync.ps1 -Token $env:_token -Mode $env:_mode -AdditionalSecrets $env:_additionalSecrets -AllVariables $env:_allVariables -AdditionalVariables $env:_additionalVariables
branding:
  icon: list
  color: blue
